strategies:
  spread_idea:
    code: spread   
    desciption: "Verbreitung der Idee des Anarchismus"
  establish_behavior_pattern:
    code: establ 
    description: "Gemeinsames ueben anarchistischer Verhaltensmuster"
  build_infrastructure:
    code: build
    description: "Aufbau anarchistischer Infrastruktur"
resources:
  happiness:
    code: happy
    description: "Wohlfuehlfaktor innerhalb der Aktiven"
  time:
    code: time
    description: "Verfuegbare Zeit"
  people:
    code: people
    description: "Anzahl der Aktiven"
actions:
  - code: demo
    description: "Lass uns eine Demo organisieren"
    costs:
      time: -1
    effects:
      happy: +3
      people: +1
      spread: +1
      establ: +1
  - code: intro
    description: "Veranstaltung 'Einfuehrung in die Anarchie'"
    costs:
      time: -1
    effects:
      happy: +1
      people: +2
      spread: +2
      establ: +1

      

      
    
