strategies:
  spread_idea:
    code: spread   
    description: "Verbreitung der Idee des Anarchismus"
  establish_behavior_pattern:
    code: establ 
    description: "Etablierung anarchistischer Verhaltensmuster"
  build_infrastructure:
    code: build
    description: "Aufbau anarchistischer Infrastruktur"
resources:
  happiness:
    code: happy
    description: "Wohlfuehlfaktor innerhalb der Aktiven"
  time:
    code: time
    description: "Verfuegbare Zeit"
  transformers:
    code: transformers
    description: "Anzahl der Transformierenden"
steps:
  - start: 
      spread: 0
      establ: 0
      build: 0
      happy: 5
      time: 5
      transformers: 1
    goal:
      spread: 10
      establ: 10
      build: 1
actions:
  - code: demo
    description: "Lass uns eine Demo organisieren"
    costs:
      time: -1
    effects:
      happy: +3
      transformers: +1
      spread: +1
      establ: +1
  - code: intro
    description: "Veranstaltung 'Einfuehrung in die Anarchie'"
    costs:
      time: -1
    effects:
      happy: +1
      transformers: +2
      spread: +2
      establ: +1

      

      
    
