strategies:
  spread_idea:
    code: spread   
    description: "Verbreitung der Idee des Anarchismus"
  establish_behavior_pattern:
    code: establ 
    description: "Etablierung anarchistischer Verhaltensmuster"
  build_infrastructure:
    code: build
    description: "Aufbau anarchistischer Infrastruktur"
resources:
  happiness:
    code: happy
    description: "Wohlfuehlfaktor innerhalb der Aktiven"
  time:
    code: time
    description: "Verfuegbare Zeit"
  transformers:
    code: transformers
    description: "Anzahl der Transformierenden"
steps:
  - description: "Noch bist du alleine mit deinen Ideen zur Transformation in eine andere Gesellschaft. Dein erstes Ziel ist es eine Gruppe mit mindestens fünf Menschen zu bilden, ein Stueck Infrastruktur aufzubauen und auf lokaler Ebene fuer die Verbreitung der Idee das Anarchismus und der Etablierung anarchistischer Verhaltensmuster zu sorgen."
    start: 
      spread: 0
      establ: 0
      build: 0
      happy: 5
      time: 5
      transformers: 1
    goal:
      spread: 10
      establ: 10
      build: 1
      transformers: 5
actions:
  - code: demo
    description: "Lass uns eine Demo organisieren"
    costs:
      time: -1
    effects:
      happy: +3
      transformers: +1
      spread: +1
      establ: +1
  - code: intro
    description: "Veranstaltung 'Einfuehrung in die Anarchie'"
    costs:
      time: -1
    effects:
      happy: +1
      transformers: +2
      spread: +2
      establ: +1

      

      
    
