debug: true
strategies:
  spread:
    description: "Verbreitung der Idee des Anarchismus"
  establ:
    description: "Etablierung anarchistischer Verhaltensmuster"
  build:
    description: "Aufbau anarchistischer Infrastruktur"
resources:
  happy:
    description: "Wohlfuehlfaktor innerhalb der Aktiven"
  time:
    description: "Verfuegbare Zeit"
  transformers:
    description: "Anzahl der Transformierenden"
steps:
  - description: "Noch bist du alleine mit deinen Ideen zur Transformation in eine andere Gesellschaft. Dein erstes Ziel ist es eine Gruppe mit mindestens fünf Menschen zu bilden, ein Stueck Infrastruktur aufzubauen und auf lokaler Ebene fuer die Verbreitung der Idee das Anarchismus und der Etablierung anarchistischer Verhaltensmuster zu sorgen."
    start: 
      spread: 0
      establ: 0
      build: 0
      happy: 5
      time: 5
      transformers: 1
    goal:
      spread: 10
      establ: 10
      build: 1
      transformers: 5
actions:
  - code: demo
    description: "Lass uns eine Demo organisieren"
    effect:
      time: -1
      happy: +3
      transformers: +1
      spread: +1
      establ: +1
  - code: intro
    description: "Veranstaltung 'Einfuehrung in die Anarchie'"
    effect:
      time: -1
      happy: +1
      transformers: +2
      spread: +2
      establ: +1
  - code: drop_out
    description: "Du kuendigst deine Lohnarbeitsanstellung"
    effect:
      build: -1
      happy: +3
      establ: +1
      transformers: +1
      time: +2
  - code: info_laden
    description: "Du eroeffnest einen Info- und Umsonstladen"
    effect: 
      time: -2
      build: +1
      establ: +2
      spread: +3
      happy: +1
  - code: wg
    description: "Du ziehst in eine WG mit netten Leuten"
    effect:
      happy: +2
      establ: +1
      time: +2
  - code: night
    description: "Du beschliesst nachts laenger wach zu bleiben, um die Transformation zu beschleunigen"
    effect:
      happy: -3
      time: +2
      establ: -1


      

      
    
