development:
  adapter: postgresql
  database: transformation
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: transformation_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: transformation
  pool: 5
  timeout: 5000
